# Form implementation generated from reading ui file 'GUI_qtDesign.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from email.mime import text

from PyQt6 import QtCore, QtGui, QtWidgets, QtMultimedia
from PyQt6.QtCore import pyqtSlot as Slot

import time as t
import glob as gl

import os
import sys

import random

from pathlib import Path

import MEISTERMASCHINE.stylesheet as style
from MEISTERMASCHINE.audio.volume import dependent_volume
from MEISTERMASCHINE.preset_utilities.preset_io import save_mms, load_mms, save_preset_json, load_preset_json
from MEISTERMASCHINE.buttons.btn_logic import btn_assign_playlist
from MEISTERMASCHINE.audio.playlist import Playlist
from MEISTERMASCHINE.audio.player_channel import PlayerChannel, PlayerController
from MEISTERMASCHINE.dice.dice_logic import roll_destiny
from MEISTERMASCHINE.sd_utilities.sd_detection import find_removable_drives
from MEISTERMASCHINE.sd_utilities.sd_worker import SDExportWorker

CHANNEL_CONFIG = {
    "music": {
        "buttons": lambda self: self.musicBtn_lst,
        "loop": True,
        "expose": True,
        "audio_index": 0,
        "max_playlist_length": 10,
    },
    "setting": {
        "buttons": lambda self: self.settingBtn_lst,
        "loop": True,
        "audio_index": 1,
        "max_playlist_length": 1,
    },
    "weather": {
        "buttons": lambda self: self.weatherBtn_lst,
        "loop": True,
        "audio_index": 2,
        "max_playlist_length": 1,
    },
    "special": {
        "buttons": lambda self: self.specialBtn_lst,
        "loop": False,
        "audio_index": 3,
        "max_playlist_length": 1,
    },
}

# accepted audio and icon file types
AUDIO_EXTS = (".mp3", ".wav", ".ogg", ".flac", ".m4a")
ICON_EXTS = (".png", ".jpg", ".jpeg", ".svg")


# ToDo: 
#   Major:
#   - implement icon tab and allow drag and drop of icons upon buttons to change them
#       > ALLOW ICON TO BE SAVED
#   - allow saving of complete presets WITH sound files so they are immune to soundfile path changes

# Minor
#   - change line when track ends and next is played (update display playlist)
#   - always show playlist of active button (leaveHoverEvent) -> done
#   - make *.mms only hold the song title and make it recombine with application path on demand
#   - when currentplaylist widget is rearranged, update button playlist
#   - add inactive play icon when playstate is stopped (play button is inactive)
#   - erase unnecessary public declarators (self.*) for garbage collection -> done
#   - shift stylesheets into own source file -> done
#   - make window resizable (or disable resize) -> done
#   - make functions to handle frame creation -> done for Utility frame
#   - make program react to audio output changes -> done


class Ui_MainWindow(QtWidgets.QWidget):
    
    def setupUi(self, MainWindow):
        ########################################################################################################
        # variables and settings
        self.btn_rows = 5
        self.channel_count = 4
        # default icons
        self.musicIcon_lst = ["icons\\smiley_star.png","icons\\smiley_grin.png","icons\\smiley_neutral.png","icons\\smiley_scary.png","icons\\smiley_death.png"]
        self.settingIcon_lst = ["icons\\pub.png","icons\\dorf.png","icons\\landschaft.png","icons\\hohle.png","icons\\kampf.png"]
        self.weatherIcon_lst = ["icons\\nacht.png","icons\\welle.png","icons\\wind.png","icons\\sturm.png","icons\\schnee.png"]
        self.specialIcon_lst = ["icons\\icon_square.png","icons\\icon_plus.png","icons\\icon_triangle.png","icons\\icon_minus.png","icons\\icon_star.png"]

        self.Btn_Display_Time = 20000   # how long is dice roll result displayed

        # get sys path depending on build condition (as *.exe or as script)
        if getattr(sys, 'frozen', False):
            # If the application is run as a bundle, the PyInstaller bootloader
            # extends the sys module by a flag frozen=True and sets the app 
            # path into variable _MEIPASS'.
            self.application_path = sys._MEIPASS
        else:
            self.application_path = os.path.dirname(__file__)

        self.srcFolder = '/Meistermaschine-Desktop-App'        # name of root directory
        self.default_soundFile_path = os.path.join(self.application_path, "sounds")
        self.default_preset_path = os.path.join(self.application_path, "presets")
        default_icon_path = os.path.join(self.application_path, "icons")

        self.preset_lst=[]
        self.btn_occupancy={}

        ########################################################################################################
        # audio control classes and objects

        # media devices change detection (changed system audio output)
        self.mediaDevices = QtMultimedia.QMediaDevices()
        self.mediaDevices.audioOutputsChanged.connect(self.on_audio_outputs_changed)

        # Create Players and add it to Channel Controller
        self.playerController = PlayerController()
        # Create Player Objects for Button Columns
        
        # music player enables position change and is displayed on interface (playlist and position)
        # setting and weather are repeated upon end of media is reached
        # special is only played once

        self.audio_output_lst = [QtMultimedia.QAudioOutput() for _ in range(self.channel_count)]
        for ao in self.audio_output_lst: 
            ao.setVolume(1.0) # initial volume is max

        for name, cfg in CHANNEL_CONFIG.items():
            audio_output = self.audio_output_lst[cfg["audio_index"]]

            channel = self.create_channel(
                name=name,
                buttons=[], # initially set empty, will be when buttons are created
                audio_output=audio_output,
                loop=cfg.get("loop", False),
                max_playlist_length=cfg.get("max_playlist_length", 40),
            )

            if cfg.get("expose"):
                setattr(self, f"{name}Channel", channel)

        # create sound buttons
        self.musicBtn_lst = [
            self.create_acceptDropButton(
                channel=self.playerController.channels["music"],
                styleSheet=style.CSS_PB_music,
                icon_path=self.musicIcon_lst[b]
            )
            for b in range(self.btn_rows)
        ]
        self.settingBtn_lst = [
            self.create_acceptDropButton(
                channel=self.playerController.channels["setting"], 
                styleSheet=style.CSS_PB_setting,
                icon_path=self.settingIcon_lst[b]
            ) 
            for b in range(self.btn_rows)
        ]
        self.weatherBtn_lst = [
            self.create_acceptDropButton(
                channel=self.playerController.channels["weather"], 
                styleSheet=style.CSS_PB_weather,
                icon_path=self.weatherIcon_lst[b]
            ) 
            for b in range(self.btn_rows)
        ]
        self.specialBtn_lst = [
            self.create_acceptDropButton(
                channel=self.playerController.channels["special"], 
                styleSheet=style.CSS_PB_special_lst[b],
                icon_path=self.specialIcon_lst[b]
            ) 
            for b in range(self.btn_rows)
        ]


        for ch in self.playerController.channels.values():
            self.connect_player_signals(ch)


        ########################################################################################################

        # main window 
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        
        
        centralwidget = QtWidgets.QWidget(parent=MainWindow)
        
        centralwidget.setObjectName("centralwidget")

        Central_Layout = QtWidgets.QGridLayout()
        Central_Layout.setSpacing(0)
        Central_Layout.setContentsMargins(0,0,0,0)

        ########################################################################################################
        # Sound Control Frame
        Sound_Frame_Layout = QtWidgets.QGridLayout()
        Sound_Frame = QtWidgets.QFrame()
        Sound_Frame.setStyleSheet(style.CSS_Sound_Frame)
        Sound_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        Sound_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        Sound_Frame.setObjectName("Sound_frame")
       
        self.playPauseButton = QtWidgets.QPushButton()
        self.playPauseButton.setStyleSheet(style.CSS_Sound_Control_Btns)
        self.playPauseButton.setText("")
        self.playIcon = QtGui.QIcon()
        self.pauseIcon = QtGui.QIcon()
        self.playIcon.addPixmap(QtGui.QPixmap(f"{default_icon_path}/icon_play.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pauseIcon.addPixmap(QtGui.QPixmap(f"{default_icon_path}/icon_pause.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.playPauseButton.setIcon(self.playIcon)
        self.playPauseButton.setIconSize(QtCore.QSize(40, 40))
        self.playPauseButton.setObjectName("playPauseButton")
        self.playPauseButton.clicked.connect(lambda: self.on_playPauseBtnClicked())

        Sound_Frame_Layout.addWidget(self.playPauseButton, 0, 0, 2, 1)

        self.trackBackwardButton = QtWidgets.QPushButton(parent=Sound_Frame)
        self.trackBackwardButton = QtWidgets.QPushButton()
        self.trackBackwardButton.setStyleSheet(style.CSS_Sound_Control_Btns)
        self.trackBackwardButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{default_icon_path}/icon_previous.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.trackBackwardButton.setIcon(icon)
        self.trackBackwardButton.setIconSize(QtCore.QSize(40, 40))
        self.trackBackwardButton.setObjectName("backwardButton")
        self.trackBackwardButton.clicked.connect(lambda: self.on_trackBackwardClicked())

        Sound_Frame_Layout.addWidget(self.trackBackwardButton, 0, 1, 2, 1)

        self.trackForwardButton = QtWidgets.QPushButton()
        self.trackForwardButton.setStyleSheet(style.CSS_Sound_Control_Btns)
        self.trackForwardButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{default_icon_path}/icon_next.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.trackForwardButton.setIcon(icon)
        self.trackForwardButton.setIconSize(QtCore.QSize(40, 40))
        self.trackForwardButton.setObjectName("forwardButton")
        self.trackForwardButton.clicked.connect(lambda: self.on_trackForwardClicked())

        Sound_Frame_Layout.addWidget(self.trackForwardButton, 0, 2, 2, 1)
        
        self.stopButton = QtWidgets.QPushButton()
        self.stopButton.setStyleSheet(style.CSS_Sound_Control_Btns)
        self.stopButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{default_icon_path}/icon_stop.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.stopButton.setIcon(icon)
        self.stopButton.setIconSize(QtCore.QSize(40, 40))
        self.stopButton.setObjectName("stopButton")
        self.stopButton.clicked.connect(lambda: self.on_stopBtnClicked())

        Sound_Frame_Layout.addWidget(self.stopButton, 0, 3, 2, 1)

        Sound_Frame_Slider_Layout = QtWidgets.QVBoxLayout()
        Sound_Frame_Slider_Widget = QtWidgets.QWidget()
        
        self.soundSlider = QtWidgets.QSlider()
        self.soundSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.soundSlider.setStyleSheet(style.CSS_soundSlider)
        self.soundSlider.setValue(0)
        self.soundSlider.setObjectName("soundSlider")
        self.soundSlider.setTracking(False)
        self.soundSlider.sliderPressed.connect(self.on_soundSliderPressed)
        self.soundSlider.sliderReleased.connect(self.on_soundSliderReleased)

        Sound_Frame_Slider_Layout.addWidget(self.soundSlider)

        self.masterVolumeSlider = QtWidgets.QSlider()
        self.masterVolumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.masterVolumeSlider.setStyleSheet(style.CSS_Slider)
        self.masterVolumeSlider.setObjectName("masterVolumeSlider")
        self.masterVolumeSlider.setRange(0, 100)
        self.masterVolumeSlider.setValue(100*int(self.playerController.channels["music"].audio_output.volume()))
        self.masterVolumeSlider.valueChanged[int].connect(self.on_masterVolumeSliderChanged)

        Sound_Frame_Slider_Layout.addWidget(self.masterVolumeSlider, alignment=QtCore.Qt.AlignmentFlag.AlignBottom)

        self.masterVolumeLabel = QtWidgets.QLabel()
        self.masterVolumeLabel.setStyleSheet(style.CSS_Label)
        self.masterVolumeLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.masterVolumeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.masterVolumeLabel.setObjectName("masterVolumeLabel")

        Sound_Frame_Slider_Layout.addWidget(self.masterVolumeLabel)
        Sound_Frame_Slider_Layout.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        Sound_Frame_Slider_Widget.setLayout(Sound_Frame_Slider_Layout)

        Sound_Frame_Layout.addWidget(Sound_Frame_Slider_Widget, 0, 4, 2, 2)

        # List widget displaying the currently active playlist (music button)
        self.currentSoundFilesListWidget = self.RearrangeListWidget()
        self.currentSoundFilesListWidget.setStyleSheet(style.CSS_List)
        self.currentSoundFilesListWidget.setObjectName("currentSoundFilesListWidget")
        self.currentSoundFilesListWidget.doubleClicked.connect(self.on_currentSoundFilesListWidget_doubleClicked)
        self.currentSoundFilesListWidget.clicked.connect(self.on_currentSoundFilesListWidget_clicked) 
        self.currentSoundFilesListWidget.itemMoved.connect(self.currentSoundFilesListWidget_itemMoved)

        Sound_Frame_Layout.addWidget(self.currentSoundFilesListWidget, 0, 6, 2, 2)
        
        # Set Layout for frame
        Sound_Frame.setLayout(Sound_Frame_Layout)
        # Add frame to central grid layout
        Central_Layout.addWidget(Sound_Frame, 4, 0, 1, 5)
       
        ########################################################################################################
        # Utilitiey frame
        # Tab 1: Dice roll interface
        # Tab 2: Audio file system and SD card management
        # Tab 3: Icon file system and interface -> ToDo

        Utility_Frame = QtWidgets.QFrame()
        Utility_Frame.setStyleSheet(style.CSS_Utility_Frame)
        Utility_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        Utility_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        Utility_Frame.setObjectName("SDframe")

        # Create a layout for the utility frame
        Utility_Frame_Layout = QtWidgets.QVBoxLayout(Utility_Frame)

        # Create the tab widget
        utilityTab = QtWidgets.QTabWidget()
        utilityTab.setStyleSheet(style.CSS_tabwidget)

        diceTab = QtWidgets.QWidget()
        audioTab = QtWidgets.QWidget()
        iconsTab = QtWidgets.QWidget()
        utilityTab.addTab(diceTab,"Dice")
        utilityTab.addTab(audioTab,"Audio")
        utilityTab.addTab(iconsTab,"Icons")

        utilityTab.setTabText(0,"Dice")
        utilityTab.setTabText(1,"Audio")
        utilityTab.setTabText(2, "Icons")

        # create layouts and add it to tab
        self.create_Dice_Tab_Layout(diceTab)

        # Tab 2: Audio file system and SD card
        self.create_Audio_Tab_Layout(audioTab)

        # Teb 3: Icons
        self.create_Icons_Tab_Layout(iconsTab)
        
        # Add the tab widget to the frame's layout
        Utility_Frame_Layout.addWidget(utilityTab)

        Utility_Frame.setLayout(Utility_Frame_Layout)

        Central_Layout.addWidget(Utility_Frame, 0, 5, 5, 2)

        #########################################################################################################
        # main interface frame (Audio Buttons)

        Interface_Frame_Layout = QtWidgets.QGridLayout()
        Interface_Frame = QtWidgets.QFrame()
        Interface_Frame.setStyleSheet(style.CSS_Interface_Frame)
        Interface_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        Interface_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        Interface_Frame.setObjectName("interfaceFrame")   
          
        # music Buttons
        for btn in self.musicBtn_lst:
            curBtnIndex = self.musicBtn_lst.index(btn)
            btn.setCheckable(True)
            btn.setText("")
            btn.setObjectName(f"musicBtn_{curBtnIndex+1}")
            btn.toggled.connect(lambda checked, b = btn: self.on_soundButtonClicked(b))
            Interface_Frame_Layout.addWidget(btn, curBtnIndex, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)

        # setting Buttons
        for btn in self.settingBtn_lst:
            curBtnIndex = self.settingBtn_lst.index(btn)
            btn.setCheckable(True)
            btn.setMaximumSize(QtCore.QSize(75, 75))
            btn.setText("")
            btn.setObjectName(f"settingBtn_{curBtnIndex+1}")
            btn.toggled.connect(lambda checked, b = btn: self.on_soundButtonClicked(b))
            Interface_Frame_Layout.addWidget(btn, curBtnIndex, 1, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)

        # weather Buttons
        for btn in self.weatherBtn_lst:
            curBtnIndex = self.weatherBtn_lst.index(btn)
            btn.setCheckable(True)
            btn.setMaximumSize(QtCore.QSize(75, 75))
            btn.setText("")
            btn.setObjectName(f"weatherBtn_{curBtnIndex+1}")
            btn.toggled.connect(lambda checked, b = btn: self.on_soundButtonClicked(b))
            Interface_Frame_Layout.addWidget(btn, curBtnIndex, 2, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)

        # special Buttons
        for btn in self.specialBtn_lst:
            curBtnIndex = self.specialBtn_lst.index(btn)
            btn.setCheckable(True)
            btn.setMaximumSize(QtCore.QSize(75, 75))
            btn.setText("")
            btn.setObjectName(f"specialBtn_{curBtnIndex+1}")
            btn.toggled.connect(lambda checked, b = btn: self.on_soundButtonClicked(b))
            Interface_Frame_Layout.addWidget(btn, curBtnIndex, 3, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignCenter)    

        # individual volume sliders
        self.musicVolumeSlider = QtWidgets.QSlider()
        self.musicVolumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.musicVolumeSlider.setStyleSheet(style.CSS_Slider)
        self.musicVolumeSlider.setObjectName("musicVolumeSlider")
        self.musicVolumeSlider.setValue(self.musicVolumeSlider.maximum())   #initial setting = max
        self.musicVolumeSlider.valueChanged.connect(self.on_musicVolumeSliderChanged)
        Interface_Frame_Layout.addWidget(self.musicVolumeSlider, 5, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.settingVolumeSlider = QtWidgets.QSlider()
        self.settingVolumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.settingVolumeSlider.setStyleSheet(style.CSS_Slider)
        self.settingVolumeSlider.setObjectName("settingVolumeSlider")
        self.settingVolumeSlider.setValue(self.settingVolumeSlider.maximum())   #initial setting = max
        self.settingVolumeSlider.valueChanged.connect(self.on_settingVolumeSliderChanged)
        Interface_Frame_Layout.addWidget(self.settingVolumeSlider, 5, 1, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.weatherVolumeSlider = QtWidgets.QSlider()
        self.weatherVolumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.weatherVolumeSlider.setStyleSheet(style.CSS_Slider)
        self.weatherVolumeSlider.setObjectName("weatherVolumeSlider")
        self.weatherVolumeSlider.setValue(self.weatherVolumeSlider.maximum())   #initial setting = max
        self.weatherVolumeSlider.valueChanged.connect(self.on_weatherVolumeSliderChanged)
        Interface_Frame_Layout.addWidget(self.weatherVolumeSlider, 5, 2, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignHCenter)

        self.specialVolumeSlider = QtWidgets.QSlider()
        self.specialVolumeSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.specialVolumeSlider.setStyleSheet(style.CSS_Slider)
        self.specialVolumeSlider.setObjectName("specialVolumeSlider")
        self.specialVolumeSlider.setValue(self.specialVolumeSlider.maximum())   #initial setting = max
        self.specialVolumeSlider.valueChanged.connect(self.on_specialVolumeSliderChanged)
        Interface_Frame_Layout.addWidget(self.specialVolumeSlider, 5, 3, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignHCenter)

        Interface_Frame.setLayout(Interface_Frame_Layout)

        Central_Layout.addWidget(Interface_Frame, 0, 0, 4, 5)

        # muffle Buttons require raw audio manipulation -> future version?
        '''self.musicMuffleButton = QtWidgets.QPushButton(parent=self.interfaceFrame)
        self.musicMuffleButton.setGeometry(QtCore.QRect(115, 415, 31, 24))
        self.musicMuffleButton.setStyleSheet(f"background-color: {dark_gray}")
        self.musicMuffleButton.setText("")
        self.musicMuffleButton.setObjectName("musicMuffleButton")

        self.settingMuffleButton = QtWidgets.QPushButton(parent=self.interfaceFrame)
        self.settingMuffleButton.setGeometry(QtCore.QRect(295, 415, 31, 24))
        self.settingMuffleButton.setStyleSheet(f"background-color: {dark_gray}")
        self.settingMuffleButton.setText("")
        self.settingMuffleButton.setObjectName("settingMuffleButton")

        self.weatherMuffleButton = QtWidgets.QPushButton(parent=self.interfaceFrame)
        self.weatherMuffleButton.setGeometry(QtCore.QRect(470, 415, 31, 24))
        self.weatherMuffleButton.setStyleSheet(f"background-color: {dark_gray}")
        self.weatherMuffleButton.setText("")
        self.weatherMuffleButton.setObjectName("weatherMuffleButton")

        self.specialMuffleButton = QtWidgets.QPushButton(parent=self.interfaceFrame)
        self.specialMuffleButton.setGeometry(QtCore.QRect(650, 415, 31, 24))
        self.specialMuffleButton.setStyleSheet(f"background-color: {dark_gray}")
        self.specialMuffleButton.setText("")
        self.specialMuffleButton.setObjectName("specialMuffleButton")

        self.muffle_label = QtWidgets.QLabel(parent=self.interfaceFrame)

        self.muffle_label.setGeometry(QtCore.QRect(48, 415, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.muffle_label.setFont(font)
        self.muffle_label.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.muffle_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.muffle_label.setObjectName("muffle_label")
        self.muffle_label.setText(_translate("MainWindow", "Muffle:"))'''

        # menu and status bars
        MainWindow.setCentralWidget(centralwidget)
        menuBar = MainWindow.menuBar()
        toolBar = MainWindow.addToolBar("File")
        toolBar.setMovable(False)
        toolBar.setStyleSheet(style.CSS_toolbar)

        # preset dropdown
        self.presetCombobox = QtWidgets.QComboBox()
        self.presetCombobox.setMinimumWidth(200)
        self.presetCombobox.setStyleSheet(style.CSS_ComboBox)
        self.presetCombobox.currentIndexChanged.connect(self.on_presetComboBoxChanged)
        presetLabel = QtWidgets.QLabel("Preset: ")
        presetLabel.setStyleSheet(style.CSS_Label)
    
        # file menu
        file_menu = menuBar.addMenu("&File")
        # new 
        icon = QtGui.QIcon.fromTheme("document-new")
        new_action = QtGui.QAction(icon, "&New...",MainWindow, triggered=self.new) 
        file_menu.addAction(new_action)
        # open 
        icon = QtGui.QIcon.fromTheme("document-open")
        open_action = QtGui.QAction(icon, "&Open...",MainWindow, triggered=self.open) 
        file_menu.addAction(open_action)
        # save
        icon = QtGui.QIcon.fromTheme("document-save")
        save_action = QtGui.QAction(icon, "&Save...",MainWindow, triggered=self.save) 
        save_action.setShortcut(QtGui.QKeySequence(QtGui.QKeySequence.StandardKey.Save))
        file_menu.addAction(save_action)
        # save as *.json
        icon = QtGui.QIcon.fromTheme("document-save")
        save_as_action = QtGui.QAction(icon, "&Save as preset",MainWindow, triggered=self.save_as_json) 
        file_menu.addAction(save_as_action)
        # save as *.mms
        icon = QtGui.QIcon.fromTheme("document-save")
        save_as_action = QtGui.QAction(icon, "&Esport to SD",MainWindow, triggered=self.save_as_mms) 
        file_menu.addAction(save_as_action)
        
        menuBar.setStyleSheet(style.CSS_menubar)
        MainWindow.setMenuBar(menuBar)
        toolBar.addWidget(menuBar)
        toolBar.addWidget(presetLabel)
        toolBar.addWidget(self.presetCombobox)
        
        
        self.statusbar = MainWindow.statusBar()
        self.statusbar.setStyleSheet(style.CSS_statusbar)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # set Layout
        centralwidget.setLayout(Central_Layout)

        # find presets and restore last preset
        self.listPresets()
        self.restore_last_preset()

        # find SD cards and populate combobox
        self.refresh_sd_cards()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def create_Icons_Tab_Layout(self, iconsTab: QtWidgets.QTabWidget)->None:
        layout = QtWidgets.QVBoxLayout(iconsTab)
        layout.setContentsMargins(6, 6, 6, 6)

        iconList = self.IconListWidget()
        iconList.setViewMode(QtWidgets.QListView.ViewMode.IconMode)
        iconList.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        iconList.setMovement(QtWidgets.QListView.Movement.Static)
        iconList.setIconSize(QtCore.QSize(48, 48))
        iconList.setSpacing(8)
        iconList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        iconList.setUniformItemSizes(True)
        iconList.setGridSize(QtCore.QSize(64, 64))
        iconList.setDragEnabled(True)
        iconList.setStyleSheet(style.CSS_List)

        layout.addWidget(iconList)

        self._populate_icon_list(iconList)

    def create_Audio_Tab_Layout(self, tab_widget: QtWidgets.QTabWidget)->None:
        Audio_Tab_Layout = QtWidgets.QGridLayout()
        
        self.fileModel = QtGui.QFileSystemModel()
        self.fileModel.setRootPath(self.default_soundFile_path)
        self.fileModel.setNameFilters(["*.mp3","*.wav", "*.ogg"]) 
        self.fileModel.setNameFilterDisables(False)
        self.fileTreeListView = QtWidgets.QTreeView()
        self.fileTreeListView.setSelectionMode(self.fileTreeListView.selectionMode().ExtendedSelection)
        self.fileTreeListView.setHeaderHidden(True)
        self.fileTreeListView.setDragEnabled(True)
        self.fileTreeListView.setStyleSheet(style.CSS_ListView)
        self.fileTreeListView.setObjectName("fileTreeListView")
        self.fileTreeListView.setModel(self.fileModel)
        self.fileTreeListView.setRootIndex(self.fileModel.index(self.default_soundFile_path))
        self.fileTreeListView.setColumnHidden(1, True)  # hide file size
        self.fileTreeListView.setColumnHidden(2, True)  # hide file type
        self.fileTreeListView.setColumnHidden(3, True)  # hide file date
        self.fileTreeListView.setColumnWidth(0, 400)
        self.fileTreeListView.show()
        self.fileTreeListView.doubleClicked[QtCore.QModelIndex].connect(self.on_fileTree_doubleClicked)

        Audio_Tab_Layout.addWidget(self.fileTreeListView, 0, 0, 6, 3)

        self.getRootFolderButton = QtWidgets.QPushButton()
        self.getRootFolderButton.setStyleSheet(style.CSS_Root_Folder_Btn)
        self.getRootFolderButton.setObjectName("getRootFolderButton")
        self.getRootFolderButton.setMaximumWidth(100)
        self.getRootFolderButton.clicked.connect(lambda: self.on_rootFolderDialogBtnClicked())

        Audio_Tab_Layout.addWidget(self.getRootFolderButton, 6, 0, 1, 1)

        SDcardsLabel = QtWidgets.QLabel()
        SDcardsLabel.setStyleSheet(style.CSS_Label)
        SDcardsLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        SDcardsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignTop)
        SDcardsLabel.setObjectName("SDcardsLabel")
        SDcardsLabel.setText("SD cards")

        Audio_Tab_Layout.addWidget(SDcardsLabel, 7, 0, 1, 1, alignment=QtCore.Qt.AlignmentFlag.AlignBottom)

        #spacer = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum) 

        #Audio_Tab_Layout.addItem(spacer, 7, 0)

        self.listOfFoundSDCardsCombobox = QtWidgets.QComboBox()
        self.listOfFoundSDCardsCombobox.setStyleSheet(style.CSS_Found_SD_Combobox)
        self.listOfFoundSDCardsCombobox.setObjectName("listOfFoundSDCardsCombobox")

        Audio_Tab_Layout.addWidget(self.listOfFoundSDCardsCombobox, 8, 0, 1, 3)



        self.refreshButton = QtWidgets.QPushButton()
        self.refreshButton.setStyleSheet(style.CSS_Refresh_SD_Btn)
        self.refreshButton.setObjectName("refreshButton")
        self.refreshButton.setFixedSize(50, 25)
        self.refreshButton.clicked.connect(self.on_refreshButton_clicked)

        Audio_Tab_Layout.addWidget(self.refreshButton, 9, 0, 1, 1)

        self.saveToSDButton = QtWidgets.QPushButton()
        self.saveToSDButton.setStyleSheet(style.CSS_Save_SD_Btn)
        self.saveToSDButton.setObjectName("saveToSDButton")
        self.saveToSDButton.clicked.connect(self.on_saveToSDButton_clicked)

        Audio_Tab_Layout.addWidget(self.saveToSDButton, 9, 2, 1, 1)

        tab_widget.setLayout(Audio_Tab_Layout)


    def create_Dice_Tab_Layout(self, tab_widget: QtWidgets.QTabWidget)->None:
        layout = QtWidgets.QGridLayout()
        minWidth = 40
        maxWidth = 60
        minHeight = 40
        maxHeight = 60

        self.dice_lst = [2, 4 ,6, 8, 10, 12, 20, 100]
        dice_stylesheet_lst = [style.CSS_Dice_Button_0, style.CSS_Dice_Button_1, style.CSS_Dice_Button_2, style.CSS_Dice_Button_3]

        self.dice_btn_lst = [QtWidgets.QPushButton() for b in range(len(self.dice_lst))]
        self.dice_txt_lst = [QtWidgets.QLabel() for l in range(len(self.dice_lst))]
        self.dice_sum_lst = [QtWidgets.QLabel() for l in range(len(self.dice_lst))]
        self.dice_timer_lst = [QtCore.QTimer() for t in range(len(self.dice_lst))]
        
        self.sum_lst = [0]*len(self.dice_lst)
        stylesheet_count=0

        result_label = QtWidgets.QLabel()
        result_label.setText("=")
        result_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        result_label.setStyleSheet(style.CSS_Label)
        result_label.setMaximumSize(30, 30)

        sum_label = QtWidgets.QLabel()
        sum_label.setText("\u03a3")
        sum_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        sum_label.setStyleSheet(style.CSS_Label)
        sum_label.setMaximumSize(40, 20)
        
        spacer_leftBorder = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding) 
        spacer_column_2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding) 
        spacer_column_4 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding) 
        spacer_rightBorder = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding) 

        layout.addItem(spacer_leftBorder, 0, 0)

        layout.addItem(spacer_column_2, 0, 2)
        layout.addWidget(result_label, 0, 3)
        layout.addItem(spacer_column_4, 0, 4)
        layout.addWidget(sum_label, 0, 5)
        layout.addItem(spacer_rightBorder, 0, 6)


        for i in range(len(self.dice_lst)):
            
            dice_Btn = self.dice_btn_lst[i]
            if stylesheet_count > 3:
                stylesheet_count=0
            dice_Btn.setStyleSheet(dice_stylesheet_lst[stylesheet_count])
            stylesheet_count+=1
            
            dice_Btn.setObjectName(f"W{self.dice_lst[i]} Button")
            dice_Btn.setText(f"W{self.dice_lst[i]}")
            dice_Btn.setMinimumSize(minWidth, minHeight)
            dice_Btn.setMaximumSize(maxWidth, maxHeight)
            dice_txt = self.dice_txt_lst[i]
            dice_txt.setText("")
            dice_txt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            dice_txt.setStyleSheet(style.CSS_Dice_Roll_Text)
            dice_txt.setMinimumSize(minWidth, minHeight)
            dice_txt.setMaximumSize(maxWidth, maxHeight)

            dice_sum = self.dice_sum_lst[i]
            dice_sum.setText("")
            dice_sum.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
            dice_sum.setStyleSheet(style.CSS_Dice_Roll_Sum)
            dice_sum.setMinimumSize(minWidth, minHeight)
            dice_sum.setMaximumSize(maxWidth, maxHeight)

            dice_timer = self.dice_timer_lst[i]
            dice_timer.setSingleShot(True)
            dice_timer.timeout.connect(lambda idx = i: self.clear_Btn(idx))

            dice_Btn.clicked.connect(lambda checked, idx = i: self.on_diceRollBtnClicked(idx))
            
            layout.addWidget(dice_Btn, i+1, 1)
            layout.addWidget(dice_txt, i+1, 3)
            layout.addWidget(dice_sum, i+1, 5)
            layout.setRowStretch(i+1, 2)
        
        # clear sum Button
        ClearSumBtn = QtWidgets.QPushButton()
        ClearSumBtn.setStyleSheet(style.CSS_Clear_Sum_Btn)
        ClearSumBtn.setObjectName("Clear Sum Button")
        ClearSumBtn.setText("X")
        ClearSumBtn.setMaximumSize(30, 30)
        ClearSumBtn.clicked.connect(lambda: self.on_clear_sum_Btn_clicked())

        layout.addWidget(ClearSumBtn, len(self.dice_lst)+1, 5, QtCore.Qt.AlignmentFlag.AlignRight)

        # Destiny Button
        DestinyBtn = QtWidgets.QPushButton()
        DestinyBtn.setStyleSheet(style.CSS_Dice_Button_4)
        DestinyBtn.setObjectName("Destiny Button")
        DestinyBtn.setText("\u2665 \u2620")
        DestinyBtn.setMinimumSize(minWidth, minHeight)
        DestinyBtn.setMaximumSize(maxWidth, maxHeight)
        self.DestinyTxt = QtWidgets.QLabel()
        self.DestinyTxt.setText("")
        self.DestinyTxt.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.DestinyTxt.setStyleSheet(style.CSS_Dice_Roll_Text)
        self.DestinyTxt.setMinimumSize(minWidth, minHeight)
        self.DestinyTxt.setMaximumSize(maxWidth, maxHeight)

        self.colorList = [style.CSS_Dice_Roll_Text_Blue, style.CSS_Dice_Roll_Text_Pink, style.CSS_Dice_Roll_Text_Yellow]
        self.current_color_index=0
        self.maxColorChanges = 20
        self.colorChanges = 0
        self.color_timer = QtCore.QTimer()
        self.color_timer.timeout.connect(lambda: self.change_color(self.DestinyTxt))
        self.destinyBtn_clear_timer = QtCore.QTimer()
        self.destinyBtn_clear_timer.setSingleShot(True)
        self.destinyBtn_clear_timer.timeout.connect(lambda: self.clear_destiny_Btn())

        DestinyBtn.clicked.connect(lambda: self.on_destinyBtnClicked(self.DestinyTxt))
        
        layout.addWidget(DestinyBtn, len(self.dice_lst)+2, 1)
        layout.addWidget(self.DestinyTxt, len(self.dice_lst)+2, 3)

        spacer_bottom = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding) 
        layout.addItem(spacer_bottom, len(self.dice_lst)+3, 0)

        layout.setRowStretch(i+2, 2)
        layout.setColumnStretch(1, 2)
        layout.setColumnStretch(3, 2)
        layout.setColumnStretch(5, 1)

        tab_widget.setLayout(layout)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Meistermaschine "))

        self.masterVolumeLabel.setText(_translate("MainWindow", "Master Volume"))
        
        # SD card control (SD_frame)
        self.getRootFolderButton.setText(_translate("MainWindow", "Change Folder"))
        self.saveToSDButton.setText(_translate("MainWindow", "Save to SD"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))

    def change_color(self, textWidget: QtWidgets.QLabel):
        if self.colorChanges < self.maxColorChanges:
            # Update the color of the QLabel
            current_color = self.colorList[self.current_color_index]
            textWidget.setStyleSheet(current_color)

            # Move to the next color in the list, looping back if necessary
            self.current_color_index = (self.current_color_index + 1) % len(self.colorList)
            self.colorChanges += 1
        else:
            self.color_timer.stop()
            textWidget.setStyleSheet(style.CSS_Dice_Roll_Text_Big)

    def clear_Btn(self, idx)->None:
        textWidget = self.dice_txt_lst[idx]
        textWidget.setText("")
        self.sum_lst[idx]=0
        sumWidget = self.dice_sum_lst[idx]
        sumWidget.setText("")

    def clear_destiny_Btn(self)->None:
        self.DestinyTxt.setText("")

    #############################################################################################################################
    # event handlers
    # Slots
    @Slot()
    def new(self) -> None:
        path, _ = QtWidgets.QFileDialog.getSaveFileName(
            None,
            "Create new preset",
            self.default_preset_path,
            "Meistermaschine Preset (*.json)"
        )
        if not path:
            return
        
        # make sure it's a *.jsaon
        if not path.lower().endswith(".json"):
            path += ".json"

        # 1) Reset current runtime state (stop audio, clear playlists, uncheck buttons, clear UI)
        self.playerController.stop_all_channels()
        self.playerController.clear_all_playlists()
        #self.uncheckAllButtons()
        self.currentSoundFilesListWidget.clear()

        # 2) Save an empty preset to the chosen path
        # Option A: save current (now empty) controller state
        save_preset_json(self.playerController, path)

        # 3) Refresh preset list + select the new one in the combobox
        self.listPresets()
        idx = self.presetCombobox.findData(path)
        if idx >= 0:
            self.presetCombobox.blockSignals(True)
            try:
                self.presetCombobox.setCurrentIndex(idx)
            finally:
                self.presetCombobox.blockSignals(False)

        # 4) Remember it as "last used"
        self._remember_last_preset(path)


    @Slot()
    def open(self) -> None:
        file = QtWidgets.QFileDialog.getOpenFileName(None, "Select a file...", self.default_preset_path, "*.json")
        if not file or not file[0]:
            return

        load_preset_json(self.playerController, file[0])
        self._remember_last_preset(file[0])
        self.listPresets()

        # select it in combobox if present
        idx = self.presetCombobox.findData(file[0])
        if idx >= 0:
            self.presetCombobox.setCurrentIndex(idx)


    @Slot()
    def import_mms(self)->None:
        file = QtWidgets.QFileDialog.getOpenFileName(None, "Select a file...", self.default_preset_path, "*.mms")
        if not file:
            return
        self.btn_occupancy = load_mms(file[0])
        btn_assign_playlist(self.musicBtn_lst, self.settingBtn_lst, self.weatherBtn_lst, self.specialBtn_lst, self.btn_occupancy)

    @Slot()
    def save(self)->None:
        file = self.getCurrentPresetFile()
        save_preset_json(self.playerController, file)

    @Slot()
    def save_as_mms(self)->None:
        file = QtWidgets.QFileDialog.getSaveFileName(None, "Save SD format", self.default_preset_path, "*.mms")
        if not file:
            return
        save_mms(file[0], self.musicBtn_lst, self.settingBtn_lst, self.weatherBtn_lst, self.specialBtn_lst)
        self.listPresets()

    @Slot()
    def save_as_json(self)->None:
        file = QtWidgets.QFileDialog.getSaveFileName(None, "Save preset", self.default_preset_path, "*.json")
        if not file:
            return
        save_preset_json(self.playerController, file[0])
        self.listPresets()

    # Button Event Handlers
    def onSongsDroppedOnButton(self, btn, paths: list[str]):
        """
        Central place where songs are added to a button playlist.
        """

        for path in paths:
            btn.playlist.add(path)

        # Optional UX decisions
        self.displayPlaylist(btn)

        # Optional: auto-activate if nothing playing
        """channel = self.playerController.find_channel_for_button(btn)
        if channel.active_button is not btn:
            btn.setChecked(True)"""

    def onPlaylistCleared(self, btn):
        self.playerController.stop_button(btn)
        self.currentSoundFilesListWidget.clear()

    # Preset Combobox
    def on_presetComboBoxChanged(self, idx) -> None:
        path = self.presetCombobox.itemData(idx)
        if not path:
            return

        self.playerController.stop_all_channels()
        load_preset_json(self.playerController, path)
        self._remember_last_preset(path)

    # audio handlers
    def on_mediaStatusChanged(self, channel, status):
        if status != QtMultimedia.QMediaPlayer.MediaStatus.EndOfMedia:
            return

        next_song = channel.get_next_track()

        if next_song:
            self.playerController.switch_track(
                channel, next_song, self.application_path, fromBeginning=True
            )
        else:
            self.playerController.deactivate_channel(channel)


    def on_playbackStateChanged(self, channel, state) -> None:
        print("playbackStateChanged", state)

        if channel is not self.musicChannel:
            return

        if state == QtMultimedia.QMediaPlayer.PlaybackState.StoppedState:
            self.soundSlider.setEnabled(False)
            self.soundSlider.setValue(0)
            self.playPauseButton.setIcon(self.playIcon)

        elif state == QtMultimedia.QMediaPlayer.PlaybackState.PausedState:
            self.soundSlider.setEnabled(True)
            self.playPauseButton.setIcon(self.playIcon)

        elif state == QtMultimedia.QMediaPlayer.PlaybackState.PlayingState:
            self.soundSlider.setEnabled(True)
            self.playPauseButton.setIcon(self.pauseIcon)

    def on_audio_outputs_changed(self):
        device = self.mediaDevices.defaultAudioOutput()

        if device.isNull():
            return

        QtCore.QTimer.singleShot(
            0,
            lambda d=device: self._apply_audio_device(d)
        )

    def _apply_audio_device(self, device):
        for ao in self.audio_output_lst:
            vol = ao.volume()
            ao.setDevice(device)
            ao.setVolume(vol)



    ##########################################################################################################################
    # Buttons
    # Dice Roll Tab in Utility Frame
    def on_clear_sum_Btn_clicked(self)->None:
        for i in range(len(self.dice_lst)):
            self.dice_sum_lst[i].setText("")
            self.sum_lst[i] = 0

    def on_diceRollBtnClicked(self, idx: int)->None:
        textWidget = self.dice_txt_lst[idx]
        sumWidget = self.dice_sum_lst[idx]
        faces = self.dice_lst[idx]
        timer = self.dice_timer_lst[idx]
        
        textWidget.setText("")
        diceRoll = random.randint(1, faces)
        textWidget.setText(str(diceRoll))
        sum = self.sum_lst[idx]
        self.sum_lst[idx] += diceRoll
        if sum!=0:
            sumWidget.setText(str(self.sum_lst[idx]))

        timer.start(self.Btn_Display_Time)
        

    def on_destinyBtnClicked(self, textWidget: QtWidgets.QLabel)->None:
        textWidget.setText("")
        
        self.color_timer.stop()
        self.colorChanges = 0

        diceRoll, outPutStr = roll_destiny()
        
        if 1 < diceRoll < 20: 
            textWidget.setStyleSheet(style.CSS_Dice_Roll_Text)
        else:
            textWidget.setStyleSheet(style.CSS_Dice_Roll_Text_Big)
            self.color_timer.start(100)  # Change color every 100 ms
        textWidget.setText(outPutStr)
        self.destinyBtn_clear_timer.start(self.Btn_Display_Time)

    def on_fileTree_doubleClicked(self)->None:
        index = self.fileTreeListView.currentIndex()
        filePath = self.fileModel.filePath(index)
        if os.path.isdir(filePath):
            self.fileTreeListView.expand(index.parent())
        # play sound file when double clicked in fileTree (SD card frame)?
        # add auxilliary player?

    def on_rootFolderDialogBtnClicked(self)->None:
        path = QtWidgets.QFileDialog.getExistingDirectory(None, "Select Folder")
        if path:
           self.fileTreeListView.setRootIndex(self.fileModel.index(path)) 

    def on_saveToSDButton_clicked(self)->None:
        self.saveToSDButton.setDown(True)
        sd_root = self.listOfFoundSDCardsCombobox.currentData()

        if not sd_root:
            QtWidgets.QMessageBox.warning(
                None,
                "No SD card selected",
                "Please select an SD card before exporting.",
            )
            return

        preset_name = self.presetCombobox.currentText().strip()
        export_dir = Path(sd_root) / preset_name

        replace_existing = False

        if export_dir.exists():
            answer = QtWidgets.QMessageBox.question(
                self,
                "Preset already exists",
                (
                    f'A preset named "{preset_name}" already exists '
                    "on the selected SD card.\n\n"
                    "Do you want to replace it?"
                ),
                QtWidgets.QMessageBox.StandardButton.Yes
                | QtWidgets.QMessageBox.StandardButton.No,
                QtWidgets.QMessageBox.StandardButton.No,
            )

            if answer != QtWidgets.QMessageBox.StandardButton.Yes:
                return

            replace_existing = True

        if not preset_name:
            QtWidgets.QMessageBox.warning(
                None,
                "No preset selected",
                "Please select or create a preset before exporting.",
            )
            return

        self.sd_export_thread = QtCore.QThread()

        self.sd_export_worker = SDExportWorker(
            sd_root=sd_root,
            preset_name=preset_name,
            application_path=self.application_path,
            music_buttons=self.musicBtn_lst,
            setting_buttons=self.settingBtn_lst,
            weather_buttons=self.weatherBtn_lst,
            special_buttons=self.specialBtn_lst,
            replace_existing=replace_existing,
        )

        self.sd_export_worker.moveToThread(
            self.sd_export_thread
        )

        self.sd_export_thread.started.connect(
            self.sd_export_worker.run
        )

        self.sd_export_worker.finished.connect(
            self.on_sd_export_finished
        )

        self.sd_export_worker.failed.connect(
            self.on_sd_export_failed
        )

        self.sd_export_worker.finished.connect(
            self.sd_export_thread.quit
        )

        self.sd_export_worker.failed.connect(
            self.sd_export_thread.quit
        )

        self.sd_export_thread.finished.connect(
            self.sd_export_worker.deleteLater
        )

        self.sd_export_thread.finished.connect(
            self.sd_export_thread.deleteLater
        )

        self.sd_progress_dialog = QtWidgets.QProgressDialog(
            "Preparing audio files...",
            None,   # no Cancel button for now
            0,
            100,
            self,
        )

        self.sd_progress_dialog.setWindowTitle("Exporting preset")
        self.sd_progress_dialog.setWindowModality(
            QtCore.Qt.WindowModality.WindowModal
        )

        self.sd_progress_dialog.setAutoClose(False)
        self.sd_progress_dialog.setAutoReset(False)
        self.sd_progress_dialog.setValue(0)
        self.sd_progress_dialog.show()

        self.sd_export_worker.progress.connect(self.on_sd_export_progress)
        self.sd_export_worker.status.connect(self.on_sd_export_status)

        self.sd_export_thread.start()
        self.saveToSDButton.setDown(False)
            
    def on_refreshButton_clicked(self) -> None:
        self.refreshButton.setDown(True)

        self.refresh_sd_cards()

        QtCore.QTimer.singleShot(
            150,
            lambda: self.refreshButton.setDown(False)
        )
    
    def on_soundButtonClicked(self, btn):
        channel = self.playerController.find_channel_for_button(btn)

        # Button turned OFF
        if not btn.isChecked():
            self.playerController.stop_button(btn)
            return

        # Button turned ON
        if channel.active_button and channel.active_button is not btn:
            self.playerController.stop_channel(channel)

        channel.active_button = btn

        """ Resume if paused??????
        # Resume if paused
        if channel.paused:
            self.playerController.resume_channel(channel)
            return"""

        song = btn.playlist.current()
        if song:
            self.playerController.switch_track(channel, song, self.application_path)
            self.displayPlaylist(btn)

    def on_stopBtnClicked(self)->None:
        self.playerController.stop_all_channels()
        self.currentSoundFilesListWidget.clear()    # clear playlist

    def on_trackBackwardClicked(self)->None:
        activeBtn = self.musicChannel.active_button
        if activeBtn:
            previousSong = activeBtn.playlist.previous()
            self.playerController.switch_track(self.musicChannel, previousSong, self.application_path)
            self.select_active_track()

    def on_trackForwardClicked(self)->None:
        activeBtn = self.musicChannel.active_button
        if activeBtn:
            nextSong = activeBtn.playlist.next()
            self.playerController.switch_track(self.musicChannel, nextSong, self.application_path)
            self.select_active_track()
    
    def on_playPauseBtnClicked(self) -> None:
        # only music reacts to it. Make all channels react???
        # if so, a global paused state has to be introduced which leads to an un-pause in 
        # the event of an addistional channel being activated while some are paused. -> checking states must be handled
        channel = self.musicChannel
        player = channel.player

        state = player.playbackState()

        # PLAYING → PAUSE
        if state == QtMultimedia.QMediaPlayer.PlaybackState.PlayingState:
            self.playerController.pause_channel(channel)
            self.playPauseButton.setIcon(self.playIcon)
            return

        # PAUSED → RESUME
        if state == QtMultimedia.QMediaPlayer.PlaybackState.PausedState:
            self.playerController.resume_channel(channel)
            self.playPauseButton.setIcon(self.pauseIcon)
            return

        # STOPPED → START (resume last active button)
        if state == QtMultimedia.QMediaPlayer.PlaybackState.StoppedState:
            btn = channel.active_button
            if not btn:
                return

            song = btn.playlist.current()
            if song:
                self.playerController.play_channel(channel, song, self.application_path, fromBeginning=False)
                self.playPauseButton.setIcon(self.pauseIcon)

    # currentSoundFilesListWidget
    def on_currentSoundFilesListWidget_clicked(self):
        item = self.currentSoundFilesListWidget.currentItem()
        if not item:
            return

        index = self.currentSoundFilesListWidget.row(item)
        self.musicChannel.play_track_at_index(
            index, self.application_path, self.playerController
        )

    def on_currentSoundFilesListWidget_doubleClicked(self):
        item = self.currentSoundFilesListWidget.currentItem()
        if not item:
            return

        index = self.currentSoundFilesListWidget.row(item)
        self.playerController.remove_track_from_channel(
            self.musicChannel, index, self.application_path
        )

        self.displayPlaylist(self.musicChannel.active_button)
    
    def currentSoundFilesListWidget_itemMoved(self, old_index, new_index) -> None:
        btn = self.playerController.channels["music"].active_button
        if not btn:
            return

        # Reorder in controller without stopping playback
        self.playerController.reorder_playlist(self.musicChannel, old_index, new_index, self.application_path)

        # Update UI selection without re-triggering playback logic
        self.currentSoundFilesListWidget.blockSignals(True)
        try:
            item = self.currentSoundFilesListWidget.item(btn.playlist.active)
            if item:
                self.currentSoundFilesListWidget.setCurrentItem(item)
                item.setSelected(True)
        finally:
            self.currentSoundFilesListWidget.blockSignals(False)

    # soundSlider
    def on_durationChanged(self, channel, duration) -> None:
        if channel is not self.musicChannel:
            return

        self.soundSlider.setMaximum(int(duration))

    def on_positionChanged(self, channel, position) -> None:
        if channel is not self.musicChannel:
            return

        self.soundSlider.setValue(int(position))

    def on_soundSliderPressed(self) -> None:
        self.playerController.pause_channel(self.musicChannel)


    def on_soundSliderReleased(self) -> None:
        position = self.soundSlider.sliderPosition()

        player = self.musicChannel.player
        player.setPosition(position)

        self.playerController.resume_channel(self.musicChannel)


    # master volume slider
    def on_masterVolumeSliderChanged(self, masterValue)->None:
        # convert linear scale to logarithmic to match dB perception
        musicValue = self.musicVolumeSlider.value()
        linMusicVolume = dependent_volume(masterValue, musicValue)
        self.playerController.channels["music"].audio_output.setVolume(linMusicVolume)

        settingValue = self.settingVolumeSlider.value()
        linSettingVolume = dependent_volume(masterValue, settingValue)
        self.playerController.channels["setting"].audio_output.setVolume(linSettingVolume)
        
        weatherValue = self.weatherVolumeSlider.value()
        linWeatherVolume = dependent_volume(masterValue, weatherValue)
        self.playerController.channels["weather"].audio_output.setVolume(linWeatherVolume)

        specialValue = self.specialVolumeSlider.value()
        linSpecialVolume = dependent_volume(masterValue, specialValue)
        self.playerController.channels["special"].audio_output.setVolume(linSpecialVolume)
        
    # individual volume sliders (dependent sliders)
    def on_musicVolumeSliderChanged(self, subValue)->None:
        masterValue = self.masterVolumeSlider.value()
        linDepVal = dependent_volume(masterValue, subValue)
        self.playerController.channels["music"].audio_output.setVolume(linDepVal)
        
    def on_settingVolumeSliderChanged(self, subValue)->None:
        masterValue = self.masterVolumeSlider.value()
        linDepVal = dependent_volume(masterValue, subValue)
        self.playerController.channels["setting"].audio_output.setVolume(linDepVal)

    def on_weatherVolumeSliderChanged(self, subValue)->None:
        masterValue = self.masterVolumeSlider.value()
        linDepVal = dependent_volume(masterValue, subValue)
        self.playerController.channels["weather"].audio_output.setVolume(linDepVal)

    def on_specialVolumeSliderChanged(self, subValue)->None:
        masterValue = self.masterVolumeSlider.value()
        linDepVal = dependent_volume(masterValue, subValue)
        self.playerController.channels["special"].audio_output.setVolume(linDepVal)
        
        
        
        
       

    #############################################################################################################################
    # helper functions

    # SD export progress dialog
    def on_sd_export_progress(
        self,
        copied_bytes: int,
        total_bytes: int,
        current_file: str,
    ) -> None:

        if total_bytes > 0:
            percent = int(
                copied_bytes / total_bytes * 100
            )
        else:
            percent = 100

        self.sd_progress_dialog.setValue(percent)

        copied_mb = copied_bytes / (1024 * 1024)
        total_mb = total_bytes / (1024 * 1024)

        self.sd_progress_dialog.setLabelText(
            f"Copying:\n{current_file}\n\n"
            f"{copied_mb:.1f} MB of {total_mb:.1f} MB"
        )

    # track when audio file format conversion to mp3 is finished during export to SD
    # to update the dialog window with the current status
    def on_sd_export_status(self, text: str) -> None:
        self.sd_progress_dialog.setLabelText(text)

    # helpers for SD export
    def on_sd_export_finished(
        self,
        export_directory: str,
    ) -> None:

        self.sd_progress_dialog.close()

        QtWidgets.QMessageBox.information(
            self,
            "Export completed",
            f"The preset was exported to:\n"
            f"{export_directory}",
        )

    def on_sd_export_failed(
        self,
        error_message: str,
    ) -> None:

        self.sd_progress_dialog.close()

        QtWidgets.QMessageBox.critical(
            self,
            "SD export failed",
            error_message,
        )

    # fins SD cards and populate combobox
    def refresh_sd_cards(self) -> None:
        self.listOfFoundSDCardsCombobox.clear()

        drives = find_removable_drives()

        for drive in drives:
            if drive.label:
                drive_letter = drive.path.rstrip("\\")
                display_name = f"{drive.label} ({drive_letter})"
            else:
                display_name = drive.path

            self.listOfFoundSDCardsCombobox.addItem(
                display_name,
                drive.path,
            )

    # make App remember preset with QSettings
    def _settings(self) -> QtCore.QSettings:
        # Pick stable names for your app
        return QtCore.QSettings("Meistermaschine", "Meistermaschine-Desktop-App")

    def _remember_last_preset(self, preset_path: str) -> None:
        if preset_path:
            preset_path = os.path.normcase(os.path.abspath(preset_path))
            self._settings().setValue("lastPresetPath", preset_path)


    def restore_last_preset(self) -> None:
        last = self._settings().value("lastPresetPath", "", str)
        if not last:
            return

        last = os.path.normcase(os.path.abspath(last))

        if not os.path.exists(last):
            return

        idx = self.presetCombobox.findData(last)
        if idx >= 0:
            # Set combobox without triggering load twice
            self.presetCombobox.blockSignals(True)
            try:
                self.presetCombobox.setCurrentIndex(idx)
            finally:
                self.presetCombobox.blockSignals(False)

            # Actually load it once
            load_preset_json(self.playerController, last)


    def _populate_icon_list(self, iconList):
        icon_dir = os.path.join(self.application_path, "icons")

        if not os.path.isdir(icon_dir):
            return

        for fname in sorted(os.listdir(icon_dir)):
            if not fname.lower().endswith((".png", ".jpg", ".jpeg", ".svg")):
                continue

            path = os.path.join(icon_dir, fname)
            icon = QtGui.QIcon(path)

            item = QtWidgets.QListWidgetItem(icon, "")
            item.setToolTip(fname)
            item.setData(QtCore.Qt.ItemDataRole.UserRole, path)

            iconList.addItem(item)


    def select_active_track(self):
        btn = self.musicChannel.active_button
        if not btn:
            return

        idx = btn.playlist.active
        item = self.currentSoundFilesListWidget.item(idx)
        if item:
            item.setSelected(True)

    def connect_player_signals(self, channel: PlayerChannel):
        p = channel.player
        p.mediaStatusChanged.connect(
            lambda status, ch=channel: self.on_mediaStatusChanged(ch, status)
        )
        p.positionChanged.connect(
            lambda pos, ch=channel: self.on_positionChanged(ch, pos)
        )
        p.durationChanged.connect(
            lambda dur, ch=channel: self.on_durationChanged(ch, dur)
        )
        p.playbackStateChanged.connect(
            lambda state, ch=channel: self.on_playbackStateChanged(ch, state)
        )
    
    def listPresets(self) -> None:
        self.presetCombobox.blockSignals(True)
        try:
            self.presetCombobox.clear()

            pattern = os.path.join(self.default_preset_path, "*.json")
            presets = gl.glob(pattern)
            presets.sort(key=os.path.getmtime, reverse=True)

            for file_path in presets:
                file_path = os.path.normcase(os.path.abspath(file_path))
                base = os.path.splitext(os.path.basename(file_path))[0]
                self.presetCombobox.addItem(base, file_path)


        finally:
            self.presetCombobox.blockSignals(False)

    def getCurrentPresetFile(self) -> str:
        file_path = self.presetCombobox.currentData()
        return file_path or ""


    def stopPlayers(self, soundPlayer_lst: list[QtMultimedia.QMediaPlayer])->None:
        for player in soundPlayer_lst:
            player.stop()
        timeout = t.time()+5    # timer set to 5 seconds
        while t.time()<timeout:    
            t.sleep(0.1)
            testVal = 0
            for player in soundPlayer_lst:
                playbackState = player.playbackState()
                if playbackState != QtMultimedia.QMediaPlayer.PlaybackState.StoppedState:
                    testVal+=1
            if testVal == 0:
                break

    def displayPlaylist(self, btn)->None:
        if not btn: return
        self.currentSoundFilesListWidget.clear()
        for sound_key in btn.playlist.tracks:
            self.currentSoundFilesListWidget.addItem(sound_key[1])   # display title
        #self.currentSoundFilesListWidget.item(btn.playlist.current()).setSelected(True)
        channel = self.playerController.find_channel_for_button(btn)
        if channel.active_button is btn:
            self.currentSoundFilesListWidget.setCurrentRow(btn.playlist.active)
        else:
            self.currentSoundFilesListWidget.setCurrentRow(-1)

    def displayActivePlaylist(self)->None:
        activeBtn = self.musicChannel.active_button
        if activeBtn:
            self.displayPlaylist(activeBtn)
        else:
            self.currentSoundFilesListWidget.clear()

    def create_channel(self, name, buttons, audio_output, loop=True, max_playlist_length=40)->PlayerChannel:
        player = QtMultimedia.QMediaPlayer()
        player.setAudioOutput(audio_output)

        channel = PlayerChannel(
            name=name,
            player=player,
            audio_output=audio_output,
            loop=loop,
            max_playlist_length=max_playlist_length,
        )

        self.playerController.add_channel(channel)
        self.connect_player_signals(channel)

        return channel

    
    class RearrangeListWidget(QtWidgets.QListWidget):
        '''
        class that implements the itemMoved signal so that the according Button playlist can be rearranged
        class enables internal drag and drop actions and scrolls automatically on drag move events up or down

        itemMoved signal is emitted with old_row and new_row which correspond to the old and new position of the moved item
        '''
        itemMoved = QtCore.pyqtSignal(int, int)

        def __init__(self, parent=None):
            super().__init__(parent)
            # Set appropriate size policy to allow resizing
            self.setSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
            self.setAcceptDrops(True)
            self.setDragEnabled(True)
            self.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
            self.scroll_timer = QtCore.QTimer(self)
            self.scroll_timer.timeout.connect(self.scroll_while_dragging)
            self.scroll_speed = 20
            self.old_row = None

        def sizeHint(self):
            # Return a reasonable size hint for the widget
            return QtCore.QSize(60, 20)  # Adjust this size as needed

        def minimumSizeHint(self):
            # Optionally, return a minimum size hint
            return QtCore.QSize(60, 20)    

        def dragEnterEvent(self, event):
            if event.mimeData().hasFormat('application/x-qabstractitemmodeldatalist'):
                event.accept()
            else:
                event.ignore()

        def dragMoveEvent(self, event):
            if event.mimeData().hasFormat('application/x-qabstractitemmodeldatalist'):
                
                self.updateListDuringDrag(event)
                #event.setDropAction(QtCore.Qt.DropAction.MoveAction)
                event.accept()
                # Start autoscrolling timer if not already started
                if not self.scroll_timer.isActive():
                    self.scroll_timer.start(20)
            else:
                event.ignore()

        def dropEvent(self, event):
            if event.mimeData().hasFormat('application/x-qabstractitemmodeldatalist'):
                new_row = self.indexAt(event.position().toPoint()).row()
                if new_row != -1:
                    old_row = self.old_row
                    if old_row != new_row:
                        item = self.takeItem(old_row)
                        self.insertItem(new_row, item)
                        self.itemMoved.emit(old_row, new_row)
                        event.accept()  
            else:
                event.ignore()

        def updateListDuringDrag(self, event):
            row = self.indexAt(event.position().toPoint()).row()
            if row != -1:
                currentItem = self.item(self.old_row)
                currentItemRow = self.row(currentItem)

                if currentItemRow < row:
                    self.insertItem(row + 1, currentItem.text())
                    self.takeItem(currentItemRow)
                elif currentItemRow > row:
                    self.insertItem(row, currentItem.text())
                    self.takeItem(currentItemRow + 1)

        def mousePressEvent(self, event):
            self.old_row = self.indexAt(event.position().toPoint()).row()
            super().mousePressEvent(event)

        def scroll_while_dragging(self):
            pos = self.mapFromGlobal(QtGui.QCursor.pos())
            if pos.y() < 0:
                self.verticalScrollBar().setValue(self.verticalScrollBar().value() - self.scroll_speed)
            elif pos.y() > self.viewport().height():
                self.verticalScrollBar().setValue(self.verticalScrollBar().value() + self.scroll_speed)

    
    class AcceptDropButton(QtWidgets.QPushButton):
        songsDropped = QtCore.pyqtSignal(object, object)
        
        playlistCleared = QtCore.pyqtSignal(object)
        playlistHovered = QtCore.pyqtSignal(object)
        playlistDropped = QtCore.pyqtSignal(object)
        playlistLeave = QtCore.pyqtSignal(object)

        def __init__(self, parent=None, channel=None, app_path="", styleSheet=None, icon_path=None):
            super().__init__(parent)

            self.setAttribute(QtCore.Qt.WidgetAttribute.WA_Hover, True)

            self.channel = channel
            self.app_path = app_path
            self.base_styleSheet = styleSheet  
            self.setStyleSheet(styleSheet) 
            self.btn_icon=icon_path
            self.set_button_icon(icon_path)

            self.playlist = Playlist(channel.max_playlist_length)

            self.setAcceptDrops(True)
            self.setSizePolicy(
                QtWidgets.QSizePolicy.Policy.Expanding,
                QtWidgets.QSizePolicy.Policy.Expanding
            )

            self._init_context_menu()


        # ---------- UI ----------

        def sizeHint(self):
            return QtCore.QSize(75, 75)

        def minimumSizeHint(self):
            return QtCore.QSize(50, 50)

        def _init_context_menu(self):
            self.menu = QtWidgets.QMenu(self)
            clear_action = self.menu.addAction("Clear Playlist")
            clear_action.triggered.connect(self.clear_playlist)

        def contextMenuEvent(self, event):
            self.menu.exec(event.globalPos())

        # ---------- Playlist ----------

        def clear_playlist(self):
            self.playlist.clear()
            self.setChecked(False)
            self.playlistCleared.emit(self)

        # ---------- Drag & Drop ----------

        def dragEnterEvent(self, event):
            if not event.mimeData().hasUrls():
                event.ignore()
                return

            has_icon = False
            has_audio = False

            for url in event.mimeData().urls():
                path = url.toLocalFile().lower()
                if path.endswith(ICON_EXTS):
                    has_icon = True
                elif path.endswith(AUDIO_EXTS):
                    has_audio = True

            if has_icon or has_audio:
                mode = "icon" if has_icon else "audio"
                self._set_drag_highlight(True, mode)
                event.acceptProposedAction()
            else:
                event.ignore()

        def dragLeaveEvent(self, event):
            self._set_drag_highlight(False)
            self.playlistLeave.emit(self)
            super().dragLeaveEvent(event)

        
        def dropEvent(self, event):
            if not event.mimeData().hasUrls():
                super().dropEvent(event)
                return

            self._set_drag_highlight(False)

            audio_paths = []
            icon_path = None

            for url in event.mimeData().urls():
                path = url.toLocalFile()

                if path.lower().endswith(ICON_EXTS):
                    try:
                        icon_path = os.path.relpath(path, self.app_path)
                    except ValueError:
                        icon_path = path  # fallback to absolute (for different drive errors)
                elif path.lower().endswith(AUDIO_EXTS):
                    rel = os.path.relpath(path, self.app_path)
                    audio_paths.append(rel)

            if icon_path:
                self.set_button_icon(icon_path)

            if audio_paths:
                self.songsDropped.emit(self, audio_paths)

            if icon_path or audio_paths:
                event.acceptProposedAction()
            else:
                event.ignore()

        def set_button_icon(self, path):
            if path:
                self.btn_icon = path
            
            abs_path = self.btn_icon
            if abs_path and not os.path.isabs(abs_path):
                abs_path = os.path.join(self.app_path, abs_path)

            self.setIcon(QtGui.QIcon(abs_path))
            self.setIconSize(QtCore.QSize(50, 50))

        def _set_drag_highlight(self, enabled, mode=None):
            if not enabled:
                self.setStyleSheet(self.base_styleSheet)
                return

            if mode == "icon":
                color = "#66ccff"
            elif mode == "audio":
                color = "#66ff99"
            else:
                color = "#aaaaaa"

            highlight = f"""
            QPushButton {{
                border: 2px dashed {color};
                background-color: {style.gray};
            }}
            """

            self.setStyleSheet(self.base_styleSheet + highlight)



        def event(self, event):
            if event.type() == QtCore.QEvent.Type.HoverEnter:
                if self.playlist.tracks:
                    self.playlistHovered.emit(self)
                return True

            if event.type() == QtCore.QEvent.Type.HoverLeave:
                self.playlistLeave.emit(self)
                return True

            return super().event(event)

        # ---------- Helpers ----------

        def _relative_path(self, url):
            return os.path.relpath(url.toLocalFile(), self.app_path)

        def _filename(self, path):
            return os.path.splitext(os.path.basename(path))[0]

    def create_acceptDropButton(self, parent=None, channel=None, styleSheet=None, icon_path=None):
        btn = self.AcceptDropButton(
            parent=parent,
            channel=channel,
            app_path=self.application_path,
            styleSheet=styleSheet,
            icon_path=icon_path
        )
        # add the button to its channel
        channel.buttons.append(btn)

         # Connect signals
        btn.playlistHovered.connect(self.displayPlaylist)
        btn.playlistCleared.connect(self.onPlaylistCleared)
        btn.playlistDropped.connect(self.displayPlaylist)
        btn.songsDropped.connect(self.onSongsDroppedOnButton)
        btn.playlistLeave.connect(self.displayActivePlaylist)

        return btn

    class IconListWidget(QtWidgets.QListWidget):
        def mimeData(self, items):
            mime = QtCore.QMimeData()
            urls = []

            for item in items:
                path = item.data(QtCore.Qt.ItemDataRole.UserRole)
                if path:
                    urls.append(QtCore.QUrl.fromLocalFile(path))

            mime.setUrls(urls)
            return mime


